<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Test");
?><?$APPLICATION->IncludeComponent(
	"bitrix:sale.bestsellers",
	"",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADDITIONAL_PICT_PROP_11" => "",
		"ADDITIONAL_PICT_PROP_13" => "",
		"ADDITIONAL_PICT_PROP_14" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_15" => "",
		"ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_6" => "MORE_PHOTO",
		"ADDITIONAL_PICT_PROP_9" => "",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"BY" => "QUANTITY",
		"CACHE_TIME" => "86400",
		"CACHE_TYPE" => "A",
		"CART_PROPERTIES_11" => "",
		"CART_PROPERTIES_13" => "",
		"CART_PROPERTIES_14" => array(0=>"CML2_LINK",1=>"",),
		"CART_PROPERTIES_15" => "",
		"CART_PROPERTIES_2" => array("BRAND_REF","CML2_MANUFACTURER",""),
		"CART_PROPERTIES_6" => "",
		"CART_PROPERTIES_9" => "",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_COMPARE" => "N",
		"FILTER" => array("CANCELED","ALLOW_DELIVERY","PAYED","DEDUCTED","N","P","F"),
		"HIDE_NOT_AVAILABLE" => "N",
		"LABEL_PROP_11" => "",
		"LABEL_PROP_13" => "",
		"LABEL_PROP_15" => "",
		"LABEL_PROP_2" => "SALELEADER",
		"LABEL_PROP_6" => "-",
		"LABEL_PROP_9" => "",
		"LINE_ELEMENT_COUNT" => "3",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"OFFER_TREE_PROPS_14" => "",
		"PAGE_ELEMENT_COUNT" => "9",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PERIOD" => "180",
		"PRICE_CODE" => array("Продажа через интернет-магазин"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_SUBSCRIPTION" => "N",
		"PROPERTY_CODE_11" => "",
		"PROPERTY_CODE_13" => "",
		"PROPERTY_CODE_14" => array(0=>"CML2_ARTICLE",1=>"",),
		"PROPERTY_CODE_15" => "",
		"PROPERTY_CODE_2" => array("",""),
		"PROPERTY_CODE_6" => "",
		"PROPERTY_CODE_9" => "",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_IMAGE" => "Y",
		"SHOW_NAME" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_PRODUCTS_11" => "N",
		"SHOW_PRODUCTS_13" => "N",
		"SHOW_PRODUCTS_15" => "N",
		"SHOW_PRODUCTS_2" => "Y",
		"SHOW_PRODUCTS_6" => "N",
		"SHOW_PRODUCTS_9" => "N",
		"TEMPLATE_THEME" => "blue",
		"USE_PRODUCT_QUANTITY" => "N"
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>